### A CI workflow template that runs linting and python testing

name: Test tap-freshservice

on: [push]

jobs:
  # tests won't pass until get resolution to: https://meltano.slack.com/archives/C03QCPY1XBQ/p1692073011277879
  # Test:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #   strategy:
  #     matrix:
  #       python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install Poetry
  #     run: |
  #       pip install poetry
  #   - name: Install dependencies
  #     run: |
  #       poetry install
  #   - name: Test with pytest
  #     run: |
  #       poetry run pytest


  BumpVersion:
    # needs: Test
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          # a special token in github at the organization account level
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # first must use the pypi organization account token, then after first publish can generate a repo-specific token
          # pypi_token: ${{ secrets.PYPI_TOKEN }}
        
  publish:
    needs: BumpVersion
    name: Upload release to PyPI
    environment:
      name: pypi
      url: https://pypi.org/p/tap-freshservice
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1